version: "3.5"

services:
  gpu_bot:
    build: .
    container_name: gpu_bot
    tty: true
    volumes:
      - ./src:/usr/src/app

  selenium-hub:
    restart: unless-stopped
    image: selenium/hub:3.14.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    restart: unless-stopped
    image: selenium/node-chrome-debug:3.14.0
    container_name: chrome
    ports:
      - "5900-5999:5900"
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
      DBUS_SESSION_BUS_ADDRESS: "/dev/null"
    links:
      - selenium-hub:hub